#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Library to build a limit order book from data generated by different agents

@author: ucaiado

Created on 08/19/2016
"""
# import libraries
from bintrees import FastRBTree
import numpy as np
import pandas as pd
import parser_data
import zipfile


'''
Begin help functions
'''


class DifferentPriceException(Exception):
    """
    DifferentPriceException is raised by the update() method in the PriceLevel
    class to indicate that the price of order object is different from the
    PriceLevel
    """
    pass


class InvalidTypeException(Exception):
    """
    InvalidTypeException is raised by the init() method in the Bookside
    class to indicate that the the book type chose is invalid
    """
    pass


def open_file(s_fname):
    '''
    Open a Zipped file and return the archice (zip object) and the file opened
    :param s_fname: string. path to the zipped file
    '''
    archive = zipfile.ZipFile(s_fname, 'r')
    fr = archive.open(archive.infolist()[0])
    return fr, archive

'''
End help functions
'''
